src/components/ProductsOption/OptionCheck.tsx
src/components/ProductsOption/OptionDepthModal.tsx
src/components/products/BottomBtn.tsx
src/states/optionAtom.ts
src/types/OptionType.ts

Feat: 상품 옵션 추가 구현 및 credential 수정

---

src/components/ProductsOption/OptionCheck.tsx
src/utils/cartApi.ts
src/utils/optionApi.ts

Fix: carts에 include 추가

---

src/app/api/auth/[...nextauth]/options.ts
src/components/Join/IdInput.tsx
src/components/Join/PwdInput.tsx
src/containers/join-email/EasyForm.tsx
src/containers/join-email/SocialPhoneCert.tsx
src/containers/join-form/AddressForm.tsx
src/containers/join-form/JoinForm.tsx

Fix: join 기능 확인, 소셜 매핑 제외 동작 확인 완료

---

src/containers/join-email/EasyForm.tsx
src/containers/join-form/JoinForm.tsx

> #111
> 소셜 회원가입 로직 백엔드에서 처리되도록 변경

Fix: 회원가입 로직 변경

---

src/app/api/auth/[...nextauth]/options.ts
src/containers/join-email/EasyForm.tsx
src/containers/join-form/JoinForm.tsx
src/containers/login/LoginForm.tsx

> #36 
> 로그인 가능, 토큰 찾는 건 추가 확인이 필요

Fix: Login

---

src/app/api/auth/[...nextauth]/options.ts
src/types/next-auth.d.ts

Feat: Session 토큰 속성 추가

---

src/app/cart/page.tsx

Fix: 비회원 빈 데이터 지정

---

src/components/Toast.tsx
src/components/products/BottomBtn.tsx

Fix: 옵션 미선택 토스트

---

src/app/cart/page.tsx
src/components/AppBar/GoToCart.tsx
src/utils/addCartNonMemberApi.ts

Fix: 비회원 장바구니 수정

---

src/app/cart/page.tsx
src/containers/cart/NonMemberCart.tsx
src/containers/cart/UserDeliveryAddress.tsx
src/utils/cartApi.ts

Fix: 비회원 장바구니 client 수정

---

src/app/cart/page.tsx

HotFix: 비회원 장바구니 에러잡기

---

src/app/cart/page.tsx

Fix: 비회원 장바구니 에러잡기

---

src/containers/cart/AllSelectHeader.tsx
src/containers/cart/NonMemberCart.tsx

Fix: 에러 로그 작성

---

src/containers/cart/CartItemCardClient.tsx
src/containers/cart/ItemInputCheckBox.tsx
src/containers/cart/NonMemberCart.tsx

Fix: 비회원 client 컴포넌트 추가

---

src/containers/cart/AllSelectHeader.tsx
src/containers/cart/NonMemberCart.tsx
src/containers/login/NonArea.tsx

Feat: 주석 해제 및 비회원 주문하기 페이지 이동

---

src/components/products/BottomBtn.tsx
src/containers/cart/CartItemCardClient.tsx
src/containers/cart/DeleteButton.tsx

Fix: 비회원 장바구니 삭제 테스트

---

src/containers/cart/NonMemberCart.tsx
src/containers/cart/UpdateCartCount.tsx

Fix: 비회원 장바구니 수량 추가 제거

---

src/containers/cart/NonMemberCart.tsx
src/states/cartAtom.ts

Fix: 비회원 cart 데이터 수정

---

src/containers/cart/NonMemberCart.tsx

Fix: 무한 루프 삭제

---

src/containers/cart/CartItemCardClient.tsx
src/containers/cart/UpdateCartCount.tsx

Fix: 장바구니 수량 추가제거 비동기 처리

---

src/app/loading.tsx
src/components/LoadingSpinner.tsx

Feat: 로딩스피너 구현

---

src/components/products/CategoryPreview.tsx
src/containers/my-clip/CategoryList.tsx
src/containers/my-clip/MyLikeFilter.tsx
src/containers/my-clip/ProductList.tsx

Fix: 카테고리 좋아요 불러오기

---

src/components/AppBar/CartCntForClient.tsx
src/components/AppBar/GoToCart.tsx
src/components/Buttons/GetCartBtn.tsx
src/states/cartAtom.ts

> #178 
> 비회원 장바구니 로직을 클라이언트 컴포넌트로 분리

Fix: 비회원 장바구니 불러오기 수정

---

.idea/inspectionProfiles/profiles_settings.xml
.idea/isekai-fe.iml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
.idea/workspace.xml
src/components/Buttons/GetCartBtn.tsx

Fix: 비동기 로직 수정

---

src/app/api/auth/[...nextauth]/options.ts

> ex) #이슈번호, #이슈번호
> 쿠키값 넣어서 로그인

Fix: 로그인 쿠키

---

src/app/api/auth/[...nextauth]/options.ts

Reverts 3-isekaiSSG/isekai-fe#206

Revert "Fix: 로그인 쿠키"
